### ISSUE TITLE
for TRA's no charts just show avg for function

### ISSUE THREAD

**Issue by daveism** [nemac/ncdeq-viewer#141]
the average is average for all tra's in the CU huc 8.  not sure 100% about this yet and need to clarify

**Comment by jdblack2** [comment]
Within an 8-digit take all the TRAs, break them up into the three bins (Hydro, WQ, and Habitat). Then take the functional score that corresponds to the TRA type (Ex. Habitat TRA and Habitat Functional Score) and average the scores together for each bin.  For example, there are 6 Habitat TRAs in Tar-Pam, each TRA has a Hydro, WQ, and Habitat Score. Because it is a Habitat TRA only average the Habitat scores for the 6 TRAs. The result will be a single value for each type of TRA.  In the provided example we would not report the hydro and WQ scores because they are less important in a Habitat TRA.

**Comment by jdblack2** [comment]
How difficult would it be to make it highlight all of the TRAs of a particular type (Hydro, Habitiat, WQ) when you click that TRAs score.  I like that currently you can click on the TRA barchart and it highlights that particular TRA in the map. That also gives the user clarity as to where the TRA Boundaries are when multiple TRAs overlap.
